### ISSUE TITLE
Release 1.0 Tracker

### ISSUE THREAD

**Issue by krshrimali** [BuffetCodes/CPP-File-Manager#17]
This issue will be closed with the launch of Release 1.0 of this project. Mention the final TODOs here:

* [x] Add documentation to the README (#16) (@HimanshuSinghGH)
* [x] Add command line argument parsing for sample code. Make sure that binary can be shared, with enough documentation in it (`-h` flag). (#18, #19) (@krshrimali)
* [x] Add documentation in the header file (@krshrimali)
* [x] Add labels for open-source contributions, triaged and more. (@krshrimali)
* [x] Final testing with enough test cases.

Let's complete the above TODOs and release 1.0 on the 4th of June.
